name: "Setup Rust Environment"
description: "Sets up Rust toolchain with protobuf compiler, caching, and optional components"
author: "nuniesmith"

branding:
    icon: "settings"
    color: "orange"

inputs:
    rust-version:
        description: "Rust version to install (e.g., stable, nightly, 1.92.0)"
        required: false
        default: "stable"
    components:
        description: "Additional components to install (comma-separated: rustfmt, clippy, llvm-tools-preview)"
        required: false
        default: "rustfmt,clippy"
    targets:
        description: "Additional targets to install (comma-separated)"
        required: false
        default: ""
    cache-key-suffix:
        description: "Suffix for cache key to differentiate between jobs"
        required: false
        default: "default"
    install-protobuf:
        description: "Install protobuf compiler"
        required: false
        default: "true"
    install-buf:
        description: "Install buf CLI for protobuf linting"
        required: false
        default: "false"
    working-directory:
        description: "Working directory for cargo commands"
        required: false
        default: "."
    cache-cargo-registry:
        description: "Cache cargo registry"
        required: false
        default: "true"
    cache-cargo-build:
        description: "Cache cargo build artifacts"
        required: false
        default: "true"
    additional-cache-paths:
        description: "Additional paths to cache (newline-separated)"
        required: false
        default: ""

outputs:
    rust-version:
        description: "Installed Rust version"
        value: ${{ steps.toolchain.outputs.rustc-version }}
    cache-hit-registry:
        description: "Whether cargo registry cache was hit"
        value: ${{ steps.cache-registry.outputs.cache-hit }}
    cache-hit-build:
        description: "Whether cargo build cache was hit"
        value: ${{ steps.cache-build.outputs.cache-hit }}

runs:
    using: "composite"
    steps:
        - name: 🦀 Install Rust toolchain
          id: toolchain
          uses: dtolnay/rust-toolchain@master
          with:
              toolchain: ${{ inputs.rust-version }}
              components: ${{ inputs.components }}
              targets: ${{ inputs.targets }}

        - name: 📦 Install protobuf compiler
          if: inputs.install-protobuf == 'true'
          shell: bash
          run: |
              echo "📦 Installing protobuf compiler..."
              sudo apt-get update -qq
              sudo apt-get install -y -qq protobuf-compiler libprotobuf-dev
              protoc --version
              echo "✅ Protobuf compiler installed"

        - name: 📦 Install buf CLI
          if: inputs.install-buf == 'true'
          uses: bufbuild/buf-setup-action@v1
          with:
              github_token: ${{ github.token }}

        - name: 📦 Cache Cargo registry
          id: cache-registry
          if: inputs.cache-cargo-registry == 'true'
          uses: actions/cache@v4
          with:
              path: |
                  ~/.cargo/bin/
                  ~/.cargo/registry/index/
                  ~/.cargo/registry/cache/
                  ~/.cargo/git/db/
              key: ${{ runner.os }}-cargo-registry-${{ inputs.cache-key-suffix }}-${{ hashFiles('**/Cargo.lock') }}
              restore-keys: |
                  ${{ runner.os }}-cargo-registry-${{ inputs.cache-key-suffix }}-
                  ${{ runner.os }}-cargo-registry-

        - name: 📦 Cache Cargo build
          id: cache-build
          if: inputs.cache-cargo-build == 'true'
          uses: actions/cache@v4
          with:
              path: |
                  target/
                  ${{ inputs.working-directory }}/target/
                  ${{ inputs.additional-cache-paths }}
              key: ${{ runner.os }}-cargo-build-${{ inputs.cache-key-suffix }}-${{ inputs.rust-version }}-${{ hashFiles('**/Cargo.lock') }}
              restore-keys: |
                  ${{ runner.os }}-cargo-build-${{ inputs.cache-key-suffix }}-${{ inputs.rust-version }}-
                  ${{ runner.os }}-cargo-build-${{ inputs.cache-key-suffix }}-

        - name: 🔧 Configure Cargo
          shell: bash
          run: |
              # Set CARGO_TERM_COLOR if not already set
              if [ -z "$CARGO_TERM_COLOR" ]; then
                echo "CARGO_TERM_COLOR=always" >> $GITHUB_ENV
              fi

              # Show installed version
              echo "🦀 Rust toolchain ready:"
              rustc --version
              cargo --version

              # Show components if installed
              if command -v rustfmt &> /dev/null; then
                rustfmt --version
              fi
              if command -v cargo-clippy &> /dev/null; then
                cargo clippy --version
              fi
