# =============================================================================
# Kraken Trading Bot - CI/CD Pipeline
# =============================================================================
# Simplified single-bot deployment in simulation mode with Discord alerts
#
# Required Secrets:
#   - TAILSCALE_OAUTH_CLIENT_ID: Tailscale OAuth Client ID
#   - TAILSCALE_OAUTH_SECRET: Tailscale OAuth Secret
#   - PROD_TAILSCALE_IP: Production server Tailscale IP
#   - PROD_SSH_KEY: SSH private key for deployment
#   - PROD_SSH_USER: SSH username (default: actions)
#   - PROD_SSH_PORT: SSH port (default: 22)
#   - DOCKER_USERNAME: Docker Hub username
#   - DOCKER_TOKEN: Docker Hub access token
#   - DISCORD_WEBHOOK_ACTIONS: Discord webhook for CI/CD notifications
#   - DISCORD_WEBHOOK_KRAKEN: Discord webhook for trading signals/alerts
#   - KRAKEN_API_KEY: Kraken API key
#   - KRAKEN_API_SECRET: Kraken API secret
# =============================================================================

name: CI/CD Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    CARGO_TERM_COLOR: always
    REGISTRY: docker.io
    IMAGE_NAME: nuniesmith/kraken

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    # =========================================================================
    # Stage 1: Test and Lint (Fast - no coverage)
    # =========================================================================
    test-and-lint:
        name: 🧪 Test and Lint
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - name: 📥 Checkout code
              uses: actions/checkout@v4

            - name: 📣 Notify build started
              continue-on-error: true
              uses: nuniesmith/actions/.github/actions/discord-notify@main
              with:
                  webhook-url: ${{ secrets.DISCORD_WEBHOOK_ACTIONS }}
                  title: "🔨 CI/CD Pipeline Started"
                  description: "Building Kraken Trading Bot"
                  status: started
                  include-repo-info: "true"

            - name: 🦀 Rust CI
              uses: nuniesmith/actions/.github/actions/rust-ci@main
              with:
                  toolchain: stable
                  run-fmt: "true"
                  run-clippy: "true"
                  run-tests: "true"
                  run-build: "true"
                  build-release: "true"
                  coverage: "false"

            - name: ✅ Notify tests passed
              if: success()
              continue-on-error: true
              uses: nuniesmith/actions/.github/actions/discord-notify@main
              with:
                  webhook-url: ${{ secrets.DISCORD_WEBHOOK_ACTIONS }}
                  title: "✅ Tests & Lint Passed"
                  description: "All tests passed successfully"
                  status: success

            - name: ❌ Notify tests failed
              if: failure()
              continue-on-error: true
              uses: nuniesmith/actions/.github/actions/discord-notify@main
              with:
                  webhook-url: ${{ secrets.DISCORD_WEBHOOK_ACTIONS }}
                  title: "❌ Tests Failed"
                  description: "CI tests failed. Check the logs for details."
                  status: failure
                  fields: '[{"name": "Workflow", "value": "[View Logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})", "inline": false}]'

    # =========================================================================
    # Stage 1c: Smoke Test Examples (PRs only)
    # =========================================================================
    smoke-test-examples:
        name: 🔬 Smoke Test Examples
        needs: test-and-lint
        runs-on: ubuntu-latest
        timeout-minutes: 15
        if: github.event_name == 'pull_request'
        steps:
            - name: 📥 Checkout code
              uses: actions/checkout@v4

            - name: 🦀 Setup Rust
              uses: dtolnay/rust-toolchain@stable

            - name: 📦 Cache cargo registry
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-cargo-examples-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-cargo-examples-

            - name: 🔨 Build examples
              run: |
                  cargo build --example paper_trading
                  cargo build --example multi_asset_trading
                  cargo build --example forward_test_live
                  cargo build --example soak_test
                  cargo build --example live_forward_test

            - name: 🧪 Run soak test (short duration)
              run: |
                  echo "Running soak test for 10 seconds..."
                  SOAK_DURATION_HOURS=0 timeout 15 cargo run --example soak_test || true
                  echo "✅ Soak test smoke test passed"

            - name: 🧪 Run forward test (short duration)
              run: |
                  echo "Running forward test for 5 seconds..."
                  timeout 10 cargo run --example forward_test_live || true
                  echo "✅ Forward test smoke test passed"

            - name: ✅ Notify smoke tests passed
              if: success()
              continue-on-error: true
              uses: nuniesmith/actions/.github/actions/discord-notify@main
              with:
                  webhook-url: ${{ secrets.DISCORD_WEBHOOK_ACTIONS }}
                  title: "🔬 Smoke Tests Passed"
                  description: "All example smoke tests completed successfully"
                  status: success

    # =========================================================================
    # Stage 2: Build and Push Docker Image
    # =========================================================================
    build-and-push:
        name: 🐳 Build and Push Docker Image
        needs: test-and-lint
        runs-on: ubuntu-latest
        timeout-minutes: 30
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        steps:
            - name: 📥 Checkout code
              uses: actions/checkout@v4

            - name: 🐳 Build and Push
              uses: nuniesmith/actions/.github/actions/docker-build-push@main
              with:
                  image-name: ${{ env.IMAGE_NAME }}
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}
                  dockerfile: docker/rust/Dockerfile
                  platforms: linux/amd64,linux/arm64

            - name: ✅ Notify Docker build complete
              if: success()
              continue-on-error: true
              uses: nuniesmith/actions/.github/actions/discord-notify@main
              with:
                  webhook-url: ${{ secrets.DISCORD_WEBHOOK_ACTIONS }}
                  title: "🐳 Docker Image Built"
                  description: "Multi-arch Docker images pushed to Docker Hub"
                  status: success
                  fields: '[{"name": "Image", "value": "${{ env.IMAGE_NAME }}:latest", "inline": true}, {"name": "Platforms", "value": "amd64, arm64", "inline": true}]'

            - name: ❌ Notify Docker build failed
              if: failure()
              continue-on-error: true
              uses: nuniesmith/actions/.github/actions/discord-notify@main
              with:
                  webhook-url: ${{ secrets.DISCORD_WEBHOOK_ACTIONS }}
                  title: "❌ Docker Build Failed"
                  description: "Failed to build or push Docker images"
                  status: failure

    # =========================================================================
    # Stage 3: Deploy to Production (Raspberry Pi)
    # =========================================================================
    deploy:
        name: 🚀 Deploy to Raspberry Pi
        needs: build-and-push
        runs-on: ubuntu-latest
        timeout-minutes: 15
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        steps:
            - name: 📥 Checkout code
              uses: actions/checkout@v4

            - name: 🔌 Connect to Tailscale
              uses: nuniesmith/actions/.github/actions/tailscale-connect@main
              with:
                  oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
                  oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
                  target-ip: ${{ secrets.PROD_TAILSCALE_IP }}
                  target-ssh-port: ${{ secrets.PROD_SSH_PORT || '22' }}

            - name: 🚀 Deploy via SSH
              id: deploy
              uses: nuniesmith/actions/.github/actions/ssh-deploy@main
              with:
                  host: ${{ secrets.PROD_TAILSCALE_IP }}
                  port: ${{ secrets.PROD_SSH_PORT || '22' }}
                  username: ${{ secrets.PROD_SSH_USER || 'actions' }}
                  ssh-key: ${{ secrets.PROD_SSH_KEY }}
                  project-path: ~/kraken
                  git-pull: false
                  git-branch: main
                  docker-pull: false
                  docker-prune: false
                  pre-deploy-command: |
                      echo "🦑 Deploying Kraken Trading Bot (Simulation Mode)..."

                      # Handle git repository setup
                      if [ ! -d "~/kraken/.git" ]; then
                        if [ -d "~/kraken" ]; then
                          echo "📁 Directory exists but is not a git repo - initializing..."
                          cd ~/kraken
                          git init
                          git remote add origin https://github.com/${{ github.repository }}.git
                          git fetch origin
                          git checkout -f main
                          git branch --set-upstream-to=origin/main main
                        else
                          echo "📥 First deployment - cloning repository..."
                          mkdir -p ~
                          git clone https://github.com/${{ github.repository }}.git ~/kraken
                          cd ~/kraken
                          git checkout main
                        fi
                      else
                        cd ~/kraken
                        echo "📥 Pulling latest changes..."
                        git fetch origin
                        git checkout main
                        git pull origin main
                      fi

                      # Ensure run.sh is executable
                      chmod +x ./run.sh 2>/dev/null || true

                      # Create .env file from template with secret substitution
                      echo "📝 Creating .env from template..."
                      cp deploy/env.template .env
                      sed -i "s|__KRAKEN_API_KEY__|${{ secrets.KRAKEN_API_KEY }}|g" .env
                      sed -i "s|__KRAKEN_API_SECRET__|${{ secrets.KRAKEN_API_SECRET }}|g" .env
                      sed -i "s|__DISCORD_WEBHOOK_URL__|${{ secrets.DISCORD_WEBHOOK_KRAKEN }}|g" .env
                      chmod 600 .env
                      echo "✅ Created .env (Simulation Mode)"

                  deploy-command: |
                      cd ~/kraken

                      # Deploy using run.sh to pull images and restart services
                      if [ -x "./run.sh" ]; then
                        echo "🐳 Stopping existing services..."
                        ./run.sh stop 2>/dev/null || true
                        echo "🐳 Pulling latest images from Docker Hub..."
                        ./run.sh start
                      else
                        echo "⚠️ run.sh not found, using docker compose directly"
                        docker compose -f docker-compose.prod.yml pull --ignore-pull-failures
                        docker compose -f docker-compose.prod.yml up -d --remove-orphans
                      fi

                  post-deploy-command: |
                      cd ~/kraken

                      echo ""
                      echo "📊 Checking container health..."
                      docker compose -f docker-compose.prod.yml ps 2>/dev/null || docker ps --format "table {{.Names}}\t{{.Status}}"

                      echo ""
                      echo "📊 Storage usage:"
                      df -h / | grep -v Filesystem
                      docker system df

                      # Prune old images to save space
                      echo ""
                      echo "🧹 Pruning unused Docker resources..."
                      docker system prune -f --volumes 2>/dev/null || true

                      echo ""
                      echo "✅ Deployment complete! (Simulation Mode - Signals Only)"

            - name: 🔍 Verify deployment
              env:
                  PROD_SSH_USER: ${{ secrets.PROD_SSH_USER || 'actions' }}
                  PROD_SSH_PORT: ${{ secrets.PROD_SSH_PORT || '22' }}
                  PI_HOST: ${{ secrets.PROD_TAILSCALE_IP }}
              run: |
                  echo "📋 Checking container logs..."

                  ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
                      -p ${PROD_SSH_PORT} -i ~/.ssh/deploy_key \
                      ${PROD_SSH_USER}@${PI_HOST} \
                      "cd ~/kraken && docker compose -f docker-compose.prod.yml logs --tail=20" || true

            - name: ✅ Notify deployment success
              if: success()
              continue-on-error: true
              uses: nuniesmith/actions/.github/actions/discord-notify@main
              with:
                  webhook-url: ${{ secrets.DISCORD_WEBHOOK_ACTIONS }}
                  title: "🚀 Deployment Successful"
                  description: "Kraken Bot deployed in **Simulation Mode** - Generating signals for manual trading"
                  status: success
                  fields: '[{"name": "Mode", "value": "🔬 Simulation", "inline": true}, {"name": "Branch", "value": "${{ github.ref_name }}", "inline": true}, {"name": "Signals", "value": "📢 Discord Alerts", "inline": true}]'

            - name: ❌ Notify deployment failed
              if: failure()
              continue-on-error: true
              uses: nuniesmith/actions/.github/actions/discord-notify@main
              with:
                  webhook-url: ${{ secrets.DISCORD_WEBHOOK_ACTIONS }}
                  title: "❌ Deployment Failed"
                  description: "Failed to deploy to Raspberry Pi"
                  status: failure
                  fields: '[{"name": "Error", "value": "Check SSH connection and Tailscale setup", "inline": false}, {"name": "Logs", "value": "[View Workflow](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})", "inline": false}]'
