service:
  name: nginx
  type: reverse-proxy
  description: "NGINX Reverse Proxy with SSL termination"
  domain: nginx.7gram.xyz
  user: nginx_user
  ports:
    - "80:80"   # HTTP
    - "443:443" # HTTPS

infrastructure:
  server_type: g6-standard-1  # 2GB RAM sufficient for NGINX
  region: ca-central
  backup_enabled: true
  
deployment:
  compose_file: docker-compose.yml
  config_dir: config/nginx
  health_check: /health
  
monitoring:
  nginx_monitoring: true
  
networking:
  tailscale_required: true
  public_access: true  # NGINX needs public access for reverse proxy
  ssl_required: true
  
users:
  service_user: nginx_user
  additional_groups:
    - docker
  
environment:
  required_secrets:
    - CLOUDFLARE_API_TOKEN
    - CLOUDFLARE_ZONE_ID
  optional_secrets:
    - SSL_EMAIL
