name: 'Docker Build & Push'
description: 'Build and push multi-arch Docker images to a registry'
author: 'nuniesmith'

branding:
  icon: 'package'
  color: 'blue'

inputs:
  registry:
    description: 'Docker registry (e.g., docker.io, ghcr.io)'
    required: false
    default: 'docker.io'
  image-name:
    description: 'Full image name (e.g., username/image)'
    required: true
  username:
    description: 'Registry username'
    required: true
  password:
    description: 'Registry password or token'
    required: true
  dockerfile:
    description: 'Path to Dockerfile'
    required: false
    default: 'Dockerfile'
  context:
    description: 'Build context path'
    required: false
    default: '.'
  platforms:
    description: 'Target platforms (comma-separated)'
    required: false
    default: 'linux/amd64,linux/arm64'
  push:
    description: 'Push image to registry'
    required: false
    default: 'true'
  tags:
    description: 'Custom tags (multiline, one per line). If empty, auto-generates tags.'
    required: false
    default: ''
  build-args:
    description: 'Build arguments (multiline KEY=VALUE)'
    required: false
    default: ''
  cache-from:
    description: 'Cache source (e.g., type=registry,ref=image:cache)'
    required: false
    default: ''
  cache-to:
    description: 'Cache destination'
    required: false
    default: ''
  labels:
    description: 'Custom labels (multiline KEY=VALUE)'
    required: false
    default: ''

outputs:
  image-id:
    description: 'Image ID'
    value: ${{ steps.build.outputs.imageid }}
  digest:
    description: 'Image digest'
    value: ${{ steps.build.outputs.digest }}
  tags:
    description: 'Generated tags'
    value: ${{ steps.meta.outputs.tags }}
  labels:
    description: 'Generated labels'
    value: ${{ steps.meta.outputs.labels }}

runs:
  using: 'composite'
  steps:
    - name: ðŸ³ Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: ðŸ³ Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: ðŸ” Log in to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: ðŸ“‹ Extract metadata (tags, labels)
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry != 'docker.io' && format('{0}/{1}', inputs.registry, inputs.image-name) || inputs.image-name }}
        tags: |
          ${{ inputs.tags != '' && inputs.tags || format('type=ref,event=branch
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}') }}

    - name: ðŸ”§ Prepare build args
      id: prepare
      shell: bash
      run: |
        # Set cache-from with fallback
        CACHE_FROM="${{ inputs.cache-from }}"
        if [ -z "$CACHE_FROM" ]; then
          CACHE_FROM="type=registry,ref=${{ inputs.image-name }}:buildcache"
        fi
        echo "cache-from=$CACHE_FROM" >> $GITHUB_OUTPUT

        # Set cache-to with fallback
        CACHE_TO="${{ inputs.cache-to }}"
        if [ -z "$CACHE_TO" ] && [ "${{ inputs.push }}" = "true" ]; then
          CACHE_TO="type=registry,ref=${{ inputs.image-name }}:buildcache,mode=max"
        fi
        echo "cache-to=$CACHE_TO" >> $GITHUB_OUTPUT

    - name: ðŸ—ï¸ Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ inputs.labels != '' && inputs.labels || steps.meta.outputs.labels }}
        platforms: ${{ inputs.platforms }}
        build-args: ${{ inputs.build-args }}
        cache-from: ${{ steps.prepare.outputs.cache-from }}
        cache-to: ${{ steps.prepare.outputs.cache-to }}

    - name: ðŸ“Š Output summary
      shell: bash
      run: |
        echo "## ðŸ³ Docker Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Property | Value |" >> $GITHUB_STEP_SUMMARY
        echo "|----------|-------|" >> $GITHUB_STEP_SUMMARY
        echo "| Image | \`${{ inputs.image-name }}\` |" >> $GITHUB_STEP_SUMMARY
        echo "| Platforms | \`${{ inputs.platforms }}\` |" >> $GITHUB_STEP_SUMMARY
        echo "| Pushed | \`${{ inputs.push }}\` |" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Tags" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
