# Example for FKS Repository
# File: .github/workflows/deploy.yml in your FKS repo

name: 🚀 Deploy FKS Service

on:
  push:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      action_type:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - 'deploy'
          - 'destroy'
          - 'health-check'
          - 'restart'
        default: 'deploy'
      
      deployment_mode:
        description: 'Deployment mode'
        required: false
        type: choice
        options:
          - 'full-deploy'
          - 'update-only'
          - 'restart-only'
          - 'code-only'
        default: 'update-only'
      
      # 🎯 Your New Options
      skip_tests:
        description: 'Skip running code tests'
        required: false
        type: boolean
        default: false
      
      skip_docker_build:
        description: 'Skip building Docker images'
        required: false
        type: boolean
        default: false
      
      build_docker_on_changes:
        description: 'Only build Docker if code/Dockerfile changed'
        required: false
        type: boolean
        default: true
      
      overwrite_server:
        description: 'Destroy and recreate Linode server'
        required: false
        type: boolean
        default: false
      
      # Destroy Options (for destroy action)
      destroy_scope:
        description: 'What to destroy (for destroy action)'
        required: false
        type: choice
        options:
          - 'service-only'
          - 'full-server'
          - 'reset-service'
        default: 'service-only'
      
      confirm_destruction:
        description: 'Type "DESTROY" to confirm destruction'
        required: false
        type: string

jobs:
  manage-fks:
    # 👇 This calls your unified actions repository
    uses: nuniesmith/actions/.github/workflows/deploy.yml@main
    with:
      service_name: fks
      action_type: ${{ github.event.inputs.action_type || 'deploy' }}
      deployment_mode: ${{ github.event.inputs.deployment_mode || 'update-only' }}
      skip_tests: ${{ github.event.inputs.skip_tests || false }}
      skip_docker_build: ${{ github.event.inputs.skip_docker_build || false }}
      build_docker_on_changes: ${{ github.event.inputs.build_docker_on_changes || true }}
      overwrite_server: ${{ github.event.inputs.overwrite_server || false }}
      destroy_scope: ${{ github.event.inputs.destroy_scope || 'service-only' }}
      confirm_destruction: ${{ github.event.inputs.confirm_destruction || '' }}
      server_type: g6-standard-4  # 8GB RAM for FKS
      target_region: ca-central
      domain_suffix: 7gram.xyz
      enable_monitoring: true
      enable_backups: false
    secrets:
      LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
      SERVICE_ROOT_PASSWORD: ${{ secrets.FKS_ROOT_PASSWORD }}
      JORDAN_PASSWORD: ${{ secrets.JORDAN_PASSWORD }}
      ACTIONS_USER_PASSWORD: ${{ secrets.ACTIONS_USER_PASSWORD }}
      TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
      TAILSCALE_OAUTH_CLIENT_ID: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
      TAILSCALE_OAUTH_SECRET: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

  # FKS-specific post-deployment
  fks-post-deploy:
    name: 🧠 FKS AI Service Setup
    runs-on: ubuntu-latest
    needs: manage-fks
    if: success() && (github.event.inputs.action_type == 'deploy' || github.event.inputs.action_type == '')
    
    steps:
      - name: 📥 Checkout FKS Repository
        uses: actions/checkout@v4

      - name: 🌐 Update Cloudflare DNS Records
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        if: env.CLOUDFLARE_API_TOKEN != '' && env.CLOUDFLARE_ZONE_ID != ''
        run: |
          echo "🌐 Updating Cloudflare DNS records for FKS AI service..."
          
          # Install jq for JSON processing
          sudo apt-get update && sudo apt-get install -y jq >/dev/null 2>&1
          
          # Get the Tailscale IP from the infrastructure job output
          TAILSCALE_IP="${{ needs.manage-fks.outputs.tailscale_ip }}"
          
          if [[ -z "$TAILSCALE_IP" || "$TAILSCALE_IP" == "unknown" || "$TAILSCALE_IP" == "pending" ]]; then
            echo "⚠️ No valid Tailscale IP available: '$TAILSCALE_IP'"
            echo "Skipping DNS update"
            exit 0
          fi
          
          echo "🔗 Using Tailscale IP: $TAILSCALE_IP"
          
          # Update A record for fks.7gram.xyz
          echo "📝 Updating A record for fks.7gram.xyz..."
          
          # Get existing record ID first
          RECORD_RESPONSE=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/dns_records?type=A&name=fks.7gram.xyz" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            -H "Content-Type: application/json")
          
          if ! echo "$RECORD_RESPONSE" | jq . >/dev/null 2>&1; then
            echo "❌ Failed to parse Cloudflare API response"
            echo "Response: $RECORD_RESPONSE"
            exit 1
          fi
          
          RECORD_ID=$(echo "$RECORD_RESPONSE" | jq -r '.result[0].id // empty')
          
          if [[ -n "$RECORD_ID" && "$RECORD_ID" != "null" ]]; then
            echo "📝 Updating existing A record (ID: $RECORD_ID)..."
            UPDATE_RESPONSE=$(curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/dns_records/$RECORD_ID" \
              -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
              -H "Content-Type: application/json" \
              --data "{
                \"type\": \"A\",
                \"name\": \"fks\",
                \"content\": \"$TAILSCALE_IP\",
                \"ttl\": 300,
                \"comment\": \"FKS AI Service - Updated by GitHub Actions\"
              }")
            
            SUCCESS=$(echo "$UPDATE_RESPONSE" | jq -r '.success // false')
            if [[ "$SUCCESS" == "true" ]]; then
              echo "✅ A record updated successfully"
            else
              echo "❌ Failed to update A record"
              echo "Response: $UPDATE_RESPONSE"
            fi
          else
            echo "📝 Creating new A record..."
            CREATE_RESPONSE=$(curl -s -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/dns_records" \
              -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
              -H "Content-Type: application/json" \
              --data "{
                \"type\": \"A\",
                \"name\": \"fks\",
                \"content\": \"$TAILSCALE_IP\",
                \"ttl\": 300,
                \"comment\": \"FKS AI Service - Created by GitHub Actions\"
              }")
            
            SUCCESS=$(echo "$CREATE_RESPONSE" | jq -r '.success // false')
            if [[ "$SUCCESS" == "true" ]]; then
              echo "✅ A record created successfully"
            else
              echo "❌ Failed to create A record"
              echo "Response: $CREATE_RESPONSE"
            fi
          fi
          
          echo "✅ DNS update completed - fks.7gram.xyz now points to $TAILSCALE_IP"
          echo "⏳ DNS propagation may take a few minutes..."

      - name: 🔗 Setup Tailscale for Post-Deploy Access
        env:
          TAILSCALE_OAUTH_CLIENT_ID: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          TAILSCALE_OAUTH_SECRET: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
        if: env.TAILSCALE_OAUTH_CLIENT_ID != '' && env.TAILSCALE_OAUTH_SECRET != ''
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
        continue-on-error: true

      - name: 🧠 Configure FKS AI Services
        env:
          SSHPASS: ${{ secrets.ACTIONS_USER_PASSWORD }}
        run: |
          echo "🧠 Configuring FKS AI services..."
          
          # Install sshpass for password authentication
          sudo apt-get update && sudo apt-get install -y sshpass >/dev/null 2>&1
          
          # Get the server IP information
          TAILSCALE_IP="${{ needs.manage-fks.outputs.tailscale_ip }}"
          echo "🔗 Server Tailscale IP: $TAILSCALE_IP"
          
          # Try to determine server connection method
          echo "🔍 Determining server connection method..."
          
          # Give SSH service time to be ready after Stage 2
          echo "⏳ Waiting for SSH service to be ready..."
          sleep 15
          
          # Method 1: Try Tailscale hostname first (most reliable)
          if timeout 15 sshpass -e ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 fks_user@fks "echo 'Connected via Tailscale hostname'" 2>/dev/null; then
            SERVER_HOST="fks"
            echo "✅ Using Tailscale hostname: $SERVER_HOST"
          # Method 2: Try Tailscale IP directly
          elif [[ -n "$TAILSCALE_IP" && "$TAILSCALE_IP" != "unknown" && "$TAILSCALE_IP" != "pending" ]] && timeout 15 sshpass -e ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 fks_user@$TAILSCALE_IP "echo 'Connected via Tailscale IP'" 2>/dev/null; then
            SERVER_HOST="$TAILSCALE_IP"
            echo "✅ Using Tailscale IP: $SERVER_HOST"
          # Method 3: Try public domain (after DNS update)
          elif timeout 15 sshpass -e ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 fks_user@fks.7gram.xyz "echo 'Connected via public domain'" 2>/dev/null; then
            SERVER_HOST="fks.7gram.xyz"
            echo "✅ Using public domain: $SERVER_HOST"
          else
            echo "❌ Could not connect to FKS server via any method"
            echo "🔍 Tried:"
            echo "  - Tailscale hostname: fks"
            echo "  - Tailscale IP: $TAILSCALE_IP"
            echo "  - Public domain: fks.7gram.xyz"
            echo "⚠️ Skipping FKS configuration"
            exit 0
          fi
          
          echo "🔄 Waiting for services to be ready..."
          sleep 30
          
          # Create service directory structure if it doesn't exist
          echo "📁 Ensuring service directory structure exists..."
          sshpass -e ssh -o StrictHostKeyChecking=no fks_user@$SERVER_HOST "
            mkdir -p /home/fks_user/fks/config
            mkdir -p /home/fks_user/fks/data
            mkdir -p /home/fks_user/fks/logs
            mkdir -p /home/fks_user/fks/models
          " || echo "⚠️ Failed to create some directories"
          
          # Upload FKS configurations if they exist
          if [[ -f "config/main.yaml" ]]; then
            echo "📁 Uploading main configuration..."
            sshpass -e scp -o StrictHostKeyChecking=no config/main.yaml fks_user@$SERVER_HOST:/home/fks_user/fks/config/ || {
              echo "⚠️ Failed to upload main config"
            }
          else
            echo "ℹ️ No main.yaml found to upload"
          fi
          
          # Upload additional configs if they exist
          if [[ -d "config/" ]]; then
            echo "📁 Uploading additional configurations..."
            sshpass -e scp -r -o StrictHostKeyChecking=no config/* fks_user@$SERVER_HOST:/home/fks_user/fks/config/ || {
              echo "⚠️ Failed to upload some configs"
            }
          fi
          
          # Upload docker-compose or other deployment files
          for file in docker-compose.yml docker-compose.yaml start.sh deploy.sh start-multi.sh; do
            if [[ -f "$file" ]]; then
              echo "📁 Uploading $file..."
              sshpass -e scp -o StrictHostKeyChecking=no "$file" fks_user@$SERVER_HOST:/home/fks_user/fks/ || {
                echo "⚠️ Failed to upload $file"
              }
            fi
          done
          
          # Check if docker-compose is ready and restart services
          echo "🐳 Checking and restarting FKS services..."
          sshpass -e ssh -o StrictHostKeyChecking=no fks_user@$SERVER_HOST "
            cd /home/fks_user/fks || exit 1
            
            echo 'Current directory contents:'
            ls -la
            
            if [[ -f docker-compose.yml ]]; then
              echo 'Docker compose file found, restarting services...'
              docker-compose down || true
              docker-compose pull || echo 'Failed to pull some images'
              docker-compose up -d || echo 'Failed to start some services'
              
              echo 'Service status:'
              docker-compose ps
            elif [[ -f start-multi.sh ]]; then
              echo 'Found start-multi.sh, running it...'
              chmod +x start-multi.sh && ./start-multi.sh
            elif [[ -f start.sh ]]; then
              echo 'Found start.sh, running it...'
              chmod +x start.sh && ./start.sh
            elif [[ -f deploy.sh ]]; then
              echo 'Found deploy.sh, running it...'
              chmod +x deploy.sh && ./deploy.sh
            else
              echo 'No start script found - manual setup may be required'
            fi
          " || {
            echo "⚠️ Failed to restart FKS services"
          }

      - name: 🧪 Test FKS Services
        run: |
          echo "🧪 Testing FKS AI services..."
          
          # Wait a bit for services to start and DNS to propagate
          echo "⏳ Waiting for services to start and DNS to propagate..."
          sleep 30
          
          TAILSCALE_IP="${{ needs.manage-fks.outputs.tailscale_ip }}"
          
          # Test web interface via multiple methods
          echo "🌐 Testing FKS API..."
          
          # Method 1: Tailscale hostname
          if timeout 10 curl -f http://fks:8080/health 2>/dev/null; then
            echo "✅ FKS API responding via Tailscale hostname"
          elif timeout 10 curl -f http://fks/health 2>/dev/null; then
            echo "✅ FKS API responding via Tailscale hostname (port 80)"
          # Method 2: Tailscale IP
          elif [[ -n "$TAILSCALE_IP" && "$TAILSCALE_IP" != "unknown" ]] && timeout 10 curl -f http://$TAILSCALE_IP:8080/health 2>/dev/null; then
            echo "✅ FKS API responding via Tailscale IP"
          elif [[ -n "$TAILSCALE_IP" && "$TAILSCALE_IP" != "unknown" ]] && timeout 10 curl -f http://$TAILSCALE_IP/health 2>/dev/null; then
            echo "✅ FKS API responding via Tailscale IP (port 80)"
          # Method 3: Public domain
          elif timeout 10 curl -f https://fks.7gram.xyz/api/health 2>/dev/null; then
            echo "✅ FKS API responding via public domain (HTTPS)"
          elif timeout 10 curl -f http://fks.7gram.xyz/health 2>/dev/null; then
            echo "✅ FKS API responding via public domain (HTTP)"
          else
            echo "⚠️ FKS API not responding via any method (may still be starting up)"
          fi
          
          # Test AI endpoints
          echo "🤖 Testing AI endpoints..."
          
          if timeout 10 curl -f http://fks/api/v1/models 2>/dev/null; then
            echo "✅ AI models endpoint accessible via Tailscale"
          elif [[ -n "$TAILSCALE_IP" && "$TAILSCALE_IP" != "unknown" ]] && timeout 10 curl -f http://$TAILSCALE_IP/api/v1/models 2>/dev/null; then
            echo "✅ AI models endpoint accessible via Tailscale IP"
          elif timeout 10 curl -f https://fks.7gram.xyz/api/v1/models 2>/dev/null; then
            echo "✅ AI models endpoint accessible via public domain"
          else
            echo "ℹ️ AI models endpoint not accessible externally (may be secured or still starting)"
          fi
          
          echo "🧠 FKS AI service setup complete!"
          echo "📊 Access URLs:"
          echo "  - Tailscale: http://fks:8080 or http://$TAILSCALE_IP:8080"
          echo "  - Public: https://fks.7gram.xyz (after DNS propagation)"
          echo "  - AI API: http://fks/api/v1/ or https://fks.7gram.xyz/api/v1/"
